config/routes.rb
TwentySecondStreet::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  root 'static_pages#home'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :picture, :styles => { :medium => "300x300>" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  belongs_to :topic, :class_name => 'Post'
  has_many :replies, :class_name => 'Post', :foreign_key => 'topic_id', dependent: :destroy
  belongs_to :user
  belongs_to :to_friend, :class_name => 'User', :foreign_key => 'to_friend_id'
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :to_friend_id, presence: true
  validates :content, presence: true, length: { maximum: 300}

  auto_html_for :content do
    html_escape
    image
    youtube(:width => "100%", :height => 200, :autoplay => false)
    vimeo(:width => 300, :height => 200, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :posts_received, :class_name => 'Post', :foreign_key=> 'to_friend_id'
  has_attached_file :avatar, :styles => { :thumb => "100x100>" },
                    :default_url => ActionController::Base.helpers.asset_path('missing_thumbnail.png')
                     # "/images/:style/missing.png"

  validates_attachment :avatar,
    :content_type => { :content_type => ["image/jpeg", "image/png"] },
    :size => { :in => 0..100.kilobytes }
  validates :password, length: { minimum: 6 }
  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    result = posts.where(topic_id: nil) + posts_received.where(topic_id: nil)
    result.sort_by {|f| f.created_at }.reverse!
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  # include BootstrapFlashHelper
  def return_point(default)
    redirect_to session[:return_point] ? session[:return_point] : default
    session.delete(:return_point)
  end

  def set_return_point(path)
    session[:return_point] = path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user,   only: :destroy

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "post created!"
      redirect_to root_url + "##{@post.id}"
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_url
  end


  private

    def post_params
      params.require(:post).permit(:to_friend_id, :content, :picture, :topic_id)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user&.authenticate(params[:password])
      sign_in user
      flash[:success] = "Welcome #{user.name}"
      return_point(user)
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @user = User.find(current_user.id)
      @single_post = @user.posts.build
      @reply = @user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :login, only: [:new, :create]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome #{@user.name}"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts_received.where(topic_id: nil).includes(:replies).paginate(page: params[:page])
    @reply = @user.posts.build
  end

  def destroy
    @user = User.find(params[:id])
    if current_user?@user
      redirect_to root_path
    else
      @user.destroy
      flash[:success] = "User deleted"
      redirect_to user_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :avatar,
                                    :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to root_path unless current_user.admin?
    end

    def login
      redirect_to root_path if signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success" # Green
      when "error"
        "alert-danger"  # Red
      when "alert"
        "alert-warning" # Yellow
      when "notice"
        "alert-info"    # Blue
    else
      flash_type.to_s
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in user
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user= user
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user? user
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    #is nil after a redirect anyway
    self.current_user = nil
  end

  def signed_in_user(new_return_point = request.url)
      # raise signed_in?.inspect
      unless signed_in?
        set_return_point(new_return_point)
        redirect_to signin_path, notice: "Please sign in."
      end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "22 street", root_path, id: "logo", class: "navbar-brand" %>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
    </div>
      <div class="collapse navbar-collapse" id="bs-navbar-collapse">
        <!-- <nav> -->
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if signed_in? %>

              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>

            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        <!-- </nav> -->
        </div>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>22 Street | <%= yield(:title) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <%= render partial: "shared/flash_messages", flash: flash %>
    <%= yield %>
    <%#= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= image_tag post.user.avatar.url(:thumb), class: "avatar_post" %>
      <a href="<%= user_path post.user %>">
        <span class="name"><%= post.user.name %></span>
      </a>
      <span class="timestamp pull-right">
        Posted <%= time_ago_in_words(post.created_at) %> ago.
      </span>

      <% if current_user?(post.user) %>
        <%= link_to "delete", post, method: :delete,
          data: { confirm: "You sure?" } %>
      <% end %>

      <p> <%= post.content_html %> </p>
      <%= image_tag post.picture.url(:medium), class: "img-responsive" if post.picture? %>
    </div>

    <div class="replies">
      <% post.replies.reverse.each do |r| %>
        <div id="<%= r.id %>" class="reply">
          <a href="<%= user_path r.user %>">
            <span class="name"><%= r.user.name %></span>
          </a>
          <span class="time"><%= time_ago_in_words(r.created_at) %></span>

          <% if current_user?(r.user) %>
            <%= link_to "delete", r, method: :delete,
            data: { confirm: "You sure?" } %>
          <% end %>
          <p> <%= r.content_html %> </p>
        </div>
      <% end %>
      <hr>
      <%= form_for @reply do |f| %>
        <p>
          <%= f.hidden_field :topic_id, :value => post.id %>
          <%= f.hidden_field :to_friend_id, :value => post.user_id %>
          <%= f.text_area :content, placeholder: "Add a comment...", class: "form-control respuesta-content" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <strong> The form contains <%= pluralize(object.errors.count, "error") %>.</strong>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= message %>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="well">
<%= form_for @single_post, :html => { :multipart => true , :class => "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.collection_select(:to_friend_id, User.all, :id, :username,
                         {prompt: "Select a friend"}, {class: "form-control"}) %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write new post...", class: "form-control" %>
  </div>
  <%= f.file_field :picture %>
  <%= f.submit "Send!", class: "btn  btn-primary" %>
<% end %>
</div>

app/views/shared/_user_info.html.erb
<div class="panel panel-default">
<%= image_tag current_user.avatar.url(:thumb), class: "avatar" %>
<h1>
  <%= current_user.username %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.posts.count, "post") %>
</span>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact me about the app at
  <a href="http://twitter.com/gabrielc63">twitter</a>.
</p>

app/views/static_pages/home.html.erb
<%# provide(:title, 'Home') %>
<% if signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/post_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <div class="row">
        <% @feed_items.each do |post| %>
          <%= render partial: "posts/post", object: post %>
        <% end %>
      </div>
      <%= will_paginate @feed_items %>
    </div>
  </div>
<% else %>

  <div class="text-center jumbotron">
    <h1>A modern social network</h1>
    <h2>This is <a>22 Street</a></h2>
    <%= link_to "Sign up!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  
<% end %>

app/views/users/_user.html.erb
<li>
    <%= image_tag user.avatar.url(:thumb), class: "avatar_post" %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
      <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" }%>
    <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :html => { :multipart => true } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.file_field :avatar %>
      </div>

      <%= f.submit "Save changes", class: "btn btn-default btn-lg btn-primary" %>
    <% end %>

    <h3>Avatar</h3>

    <%= image_tag @user.avatar.url(:thumb) %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/index.js.erb
$('.users').append('<%= j render(@users) %>');
<% if @users.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@users) %>');
<% else %>
  $('.pagination').remove()
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.file_field :avatar %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-default btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= image_tag @user.avatar.url(:thumb), class: "avatar" %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.posts_received.any? %>
      <h3>Messages (<%= @user.posts_received.count %>)</h3>
      <div class="row">
        <%= render @posts %>
      </div>
      <%= will_paginate @posts %>
    <% end %>
  </div>
</div>